name: Build APK

on:
  push:
    branches:
      - main  # Replace with your branch name if needed
  pull_request:
    branches:
      - main  # Replace with your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Choose the appropriate Python version

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            build-essential \
            ccache \
            libffi-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            pkg-config \
            libgl-dev \
            libgles2-mesa-dev \
            python3-pip
          pip install buildozer
          pip install cython  # Install Cython

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip -d cmdline-tools
          echo 'export ANDROID_SDK_ROOT=$HOME/cmdline-tools' >> $GITHUB_ENV
          echo 'export PATH=$PATH:$HOME/cmdline-tools/tools/bin:$HOME/cmdline-tools/platform-tools' >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Build APK
        run: buildozer -v android debug

